### ISSUE TITLE
Bot commands issue

### ISSUE THREAD

**Issue by HonkingGoose** [HonkingGoose/try-out-all-contributors-bot#2]
Empty issue to comment commands for the bot.

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for code

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for maintenance

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for ideas

**Comment by rarkins** [comment]
@all-contributors please add @rarkins for free

**Comment by rarkins** [comment]
@all-contributors please add @rarkins for mentoring

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for code

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for code

**Comment by HonkingGoose** [comment]
@all-contributors please add @HonkingGoose for design
